### ISSUE TITLE
Mail.RU bot in bad_user_agents

### ISSUE THREAD

**Issue by eukos** [crowdsecurity/sec-lists#30]
Can you please exclude the `Mail.RU_Bot` UA from both [web/bad_user_agents.txt](https://github.com/crowdsecurity/sec-lists/blob/4f0e3252af0c9f028cc9b0618d9f34c35cbf4d4c/web/bad_user_agents.txt) and [web/bad_user_agents.regex.txt](https://github.com/crowdsecurity/sec-lists/blob/26a6a9cf7a9f9b5c5792727edaf916d3ac692ba3/web/bad_user_agents.regex.txt)

It looks like this is official bot for mail.ru search: https://help.mail.ru/webmaster/indexing/robots/robot_log

**Comment by AlteredCoder** [comment]
Hello,

We have removed the user agent from the list.
To update your list, you can run `cscli scenarios upgrade --force crowdsecurity/http-bad-user-agent`

**Comment by eukos** [comment]
Hello,
thank you!
