### ISSUE TITLE
WeChat blocked in bad_user_agents.regex

### ISSUE THREAD

**Issue by PHPGangsta** [crowdsecurity/sec-lists#44]
Hello,

WeChat seems to be on your "bad_user_agents" list:
https://raw.githubusercontent.com/crowdsecurity/sec-lists/master/web/bad_user_agents.regex.txt

This is a WeChat user-agent:

`User-Agent: Mozilla/5.0 (Linux; Android 12; moto g(30) Build/S0RCS32.41-10-19-3; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.99 XWEB/4263 MMWEBSDK/20220604 Mobile Safari/537.36 MMWEBID/6045 MicroMessenger/8.0.24.2167(0x28001843) WeChat/arm64 Weixin GPVersion/1 NetType/WIFI Language/en ABI/arm64`

The bad_user_agents.regex.txt file contains following line:
`\bMicroMessenger\b`

This seems to be the reason for blocking the IP/Client after a few requests.

Here is a list of WeChat User Agents, all of them contain the word "MicroMessenger":
https://developers.whatismybrowser.com/useragents/explore/software_name/wechat/

**Comment by System233** [comment]
Repository not maintained. 
To everyone who has the same problem🙁:
```shell
cscli scenarios remove crowdsecurity/http-bad-user-agent
systemctl reload crowdsec
```

**Comment by williamdes** [comment]
This is bad feedback @buixor

**Comment by LaurenceJJones** [comment]
Hey 👋🏻 

This is a little tricky as some people may not want these useragents. You can add this exception yourself by just editting the text file within the data directory to remove it  but thats "what you class as a false positive" as others may not see it as one.

I will talk with the team about this

**Comment by LaurenceJJones** [comment]
Hey we pushed #49 but how the data files work this update wont be repulled so you **MUST** do

```
cscli scenarios install crowdsecurity/http-bad-user-agent --force
```

You must include the force option as by default crowdsec tries to not download it if the file exits
